name: Example Wily Pipeline on PR

on:
  pull_request:
    branches:
      - main

jobs:
  evaluate-complexity:
    name: Evaluate Code complexity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Wily
        run: pip install wily==1.20.0
      - name: Build cache and diff
        id: wily
        run: |
          wily build .
          DIFF=$(wily diff . --no-detail -r origin/${{ github.event.pull_request.base.ref }})
          echo "$DIFF"

          # Build multine output
          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "::set-output name=diff::$DIFF"
      - name: Show wily report
        run: |
          wily report refactoring_220812
          REPORT=$(wily report refactoring_220812)
          message: REPORT
      - name: Show wily rank
        run: |
          wily rank .
