wily:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2-beta
    with:
      fetch-depth: 0

  - uses: actions/checkout@v2-beta
    with:
      ref: refs/heads/main
      clean: false

  - name: Set up Python 3.8
    uses: actions/setup-python@v1
    with:
      python-version: "3.8"

  - name: Install dependencies
    run:
      python -m pip install --upgrade pip
      python -m pip install wily
  - name: Build wily
    run:
      wily build refactoring_220812/ .
      wily diff refactoring_220812/ -r master
  - name: Show wily report
    run:
      wily report refactoring_220812
  - name: Show wily rank
    run:
      wily rank refactoring_220812/