name: Example Wily Pipeline on PR

on:
  pull_request:
    branches:
      - main

jobs:
  evaluate-complexity:
    name: Evaluate Code complexity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Wily
        run: pip install wily==1.20.0
      - name: Build Wily
        id: wily
        run: |
          wily build .
      - name: Show Wily report
        run: |
          wily report refactoring_220812
      - name: Add Wily PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.wily.outputs.diff != ''
        with:
          recreate: true
          message: |
            ```
            ${{ steps.wily.outputs }}
            ```
      - name: Add Wily PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.wily.outputs == ''
        with:
          recreate: true
          message: |
            ```
            Wily: No changes in complexity detected.
            ```