name: Example Wily Pipeline on PR

on:
  pull_request:
    branches:
      - main

jobs:
  evaluate-complexity:
    name: Evaluate Code complexity
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wily
      - name: Build wily
        run: |
          wily build .
      - name: Show wily report
        run: |
          wily report .
